.TH MX-MENU-EDITOR 1 "August 2026" "MX Linux" "User Commands"
.SH NAME
mx-menu-editor \- editor for Xfce application menus
.SH SYNOPSIS
.B mx-menu-editor
.SH DESCRIPTION
.B mx-menu-editor
is a graphical tool for editing the Xfce application menu on MX Linux.
It lets the user show or hide applications, edit the properties of
existing desktop launchers, and create custom application launchers,
without editing
.I .desktop
files by hand.
.SH SEE ALSO
.BR xfce4\-panel (1)
